#name: p2p
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py39hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py39h06a4308_0
  - cffi=2.0.0=py39h4eded50_0
  - charset-normalizer=3.4.4=py39h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=h5eee18b_0
  - eigen=3.4.0=h171cf75_1
  - expat=2.7.3=h3385a95_0
  - ffmpeg=6.1.1=hecf7045_5
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=h5eee18b_0
  - glog=0.5.0=h48cff8f_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.12=hc146dc4_1
  - gstreamer=1.24.12=hb6d4d65_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - idna=3.11=py39h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jpeg=9f=h5ce9db8_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_hbbce691_0
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.1.1=h0131e85_1
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=ha7bfdaf_5
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h27cfd23_1
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h501fc15_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=h6a678d5_1
  - mesalib=25.1.5=h31e3550_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py39hacdc0fc_0
  - mkl_fft=1.3.11=py39hacdc0fc_1
  - mkl_random=1.3.0=py39h505adc9_0
  - mysql-common=9.3.0=h266115a_0
  - mysql-libs=9.3.0=he0572af_0
  - ncurses=6.5=h7934f7d_0
  - opencv=4.12.0=py39hc7c50f1_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.46=hf426167_0
  - pillow=11.3.0=py39hb1c3d2d_0
  - pip=23.3.1=py39h06a4308_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_1
  - python=3.9.25=h0dcde21_1
  - pytorch-mutex=1.0=cuda
  - qtbase=6.9.2=hd13baf8_5
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py39h06a4308_0
  - setuptools=80.9.0=py39h06a4308_0
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - typing_extensions=4.15.0=py39h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==0.18.0
      - asttokens==3.0.1
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - diffusers==0.14.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - hf-xet==1.2.0
      - huggingface-hub==0.13.4
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - regex==2025.11.3
      - safetensors==0.7.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tokenizers==0.13.2
      - torch==2.8.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.26.1
      - triton==3.4.0
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
#prefix: /root/autodl-tmp/conda/envs/p2p
